
server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force: true

spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: ${DB_URL}
    driver-class-name: ${DB_DRIVER_CLASS_NAME}
    hikari:
      maximum-pool-size: ${DB_POOL_SIZE}
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  data:
    redis:
      host: localhost
      port: 6379
  sql:
    init:
      mode: always



key:
  latest:
      price: latest_trading_price