
server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force: true

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://mysql:3306/springbootapp?useSSL=false&useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 5
    username: root
    password: root
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  data:
    redis:
      host: redis
      port: 6379
  sql:
    init:
      mode: always



key:
  latest:
      price: latest_trading_price